# Font, my favorite font is maple mono :)
font_family Maple Mono

# Make the cursor shape a beam
shell_integration no-cursor
cursor_shape beam

# Padding
window_padding_width 7
window_padding_height 10

# Scroll back up to 3000 lines.
scrollback_lines 3000

#Default font size.
font_size 12

# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 0.8


# Finally, the COLORS! these use the design system I made for this rice.
cursor               #abbcda

selection_background #FBF8CC
selection_foreground #090708

background           #090708
foreground           #FBF8CC

color0               #b9fbc0
color8               #98f5e1
color1               #8eecf5
color9               #8eecf5
color2               #90dbf4
color10              #90dbf4
color3               #a3c4f3
color11              #a3c4f3
color4               #cfbaf0
color12              #cfbaf0
color5               #f1c0e8
color13              #f1c0e8
color6               #ffcfd3
color14              #ffcfd2
color7               #fde4cf
color15              #FBF8CC
